### ISSUE TITLE
Shared memory for notebooks set to 64Mb

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/kubeflow#111]
Description of problem:
Jupyter notebooks deployed by RHODS have the shared memory (/dev/shm) set to 64 MB. There doesn't appear to be any way to change this default. This creates issues with Pytorch running multiple workers on GPU-enabled nodes. Multiple workers significantly speed up training tasks, but a 64Mb limit forces the user to disable multiple workers. The increase in performance can be an order of magnitude faster and utilizes GPUs more optimally. 

Prerequisites (if any, like setup, operators/versions):
Steps to Reproduce
Deploy a Jupyter notebook.
Clone a repo that uses Pytorch. In my case https://github.com/ultralytics/yolov5
After running "pip install -r requirements.txt" run "python train.py" with no arguments. 
Actual results:
Jupyter will report "no space left on device" and you will notice /dev/smh is full.

Expected results:
The training script should begin running 100 epochs on the training data without error.

JIRA Issue: [RHODS-8939](https://issues.redhat.com//browse/RHODS-8939)

**Comment by harshad16** [comment]
The change is now merged in the v1.7 branches.
Closing this issue as it is completed here.

**Comment by harshad16** [comment]
As we don't want to disrupt long-running notebooks, we are reverting these changes
it would be introduced via Notebook CR, instead of statefulset injection.

**Comment by harshad16** [comment]
This would be re-introduced in ODH-dashboard by updating notebook CR.

**Comment by shalberd** [comment]
on the assembleNotebook side of odh-dashboard code, yes, good idea

**Comment by harshad16** [comment]
The Elyra way is for the pipeline tasks to have the shared memory right ?
this is for the notebook pods to have it as well, so data-scientist can work on their model without issue.

**Comment by guimou** [comment]
Yes, in Elyra you can set this is as part of the runtime config. For notebooks right now, PyTorch is almost unusable for mildly large training...

**Comment by shalberd** [comment]
> For notebooks right now, PyTorch is almost unusable for mildly large training...

@guimou not anymore, thanks to Harshad

https://github.com/opendatahub-io/odh-dashboard/pull/1594

You should be able to test with the nightly or main tag of odh-dashboard

https://quay.io/repository/opendatahub/odh-dashboard?tab=tags

in custom-manifests, placed here on your own:

https://github.com/opendatahub-io/odh-manifests/blob/master/odh-dashboard/base/kustomization.yaml#L28

**Comment by harshad16** [comment]
Fixed this issue with odh-dashboard.
dashboard which creates the notebook CR, would include the volume-mount `shm` to the notebook.
details: https://github.com/opendatahub-io/odh-dashboard/pull/1594

It would be available in both 1.8 and onwards.
closing the issue.
