### ISSUE TITLE
JupyterLab / RStudio won't open on Kubeflow on OpenDataHub 

### ISSUE THREAD

**Issue by romeokienzler** [opendatahub-io/kubeflow#12]
/kind bug

**What steps did you take and what happened:**
JupyterLab / RStudio won't open on Kubeflow on OpenDataHub 
Error when clicking on "connect:

upstream connect error or disconnect/reset before headers. reset reason: connection failure

**What did you expect to happen:**
JupyterLab / RStudio open on Kubeflow on OpenDataHub 

**Anything else you would like to add:**
![image](https://user-images.githubusercontent.com/5694071/161724804-a9fcbaa5-7c6f-4ea1-a501-f15a0e59a226.png)

**Environment:**
- openshift:4.8.31_1546 on IBM Cloud
- ODH operator 1.1.2 stable
- Kubeflow version:  build version dev_local (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: (use `kfctl version`):
- Kubernetes platform: openshift
- Kubernetes version: openshift:4.8.31_1546

**Comment by harshad16** [comment]
With the current set of images.
The R-studio and jupyterlab both are functional with the notebook-controller being used in OpenDatahub.
Closing this issue. Please re-open if you feel there is some issue.
