### ISSUE TITLE
[Bug]: After updating the config map in the workbench the pods are not restarted 

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/kubeflow#165]
/kind bug

**What steps did you take and what happened:**

As an ODH User when I try to update the env var in workbenches, the env var does not get reflected in the notebook.
The pods don't get restarted. We need to create a method to restart pods from the statefulset.

**What did you expect to happen:**
Updating the env var config map, updates the pods of the notebook.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Perhaps, we can use annotation to make sure, the pods get restarted by the statefulset.

**Comment by harshad16** [comment]
Approach the problem:

1. Use annotation to scale pods up/down. 
The controller would scale the pods based on the annotation set on the notebook CR. user/any other tool would need to update the annotation on the notebook CR, if they would like to scale the pod when not changing any statefulset kinda of resource. 

2.  Watch configmap attached to Notebook CR, for any updates.
Based on the configmap attached to the Notebook CR, make the controller watch the configmap resource, if there are any updates to the configmap, scale the pod to pickup the resource changes.

**Comment by harshad16** [comment]
Based on the 2 approaches, the plan is to follow the 1 approach, due to the following reasons:
1. Approach 1 would allow notebook-controller to be notebook CR scoped and no need to watch additional resource.
and annotation method would allow , future use in any other place, whenever pods are needed to be scaled.
2. Approach 2 would require notebook-controller to watch additional resource, which could requires additional permission on notebook-controller service-account.

**Comment by harshad16** [comment]
The procedure of working:

1. What approach to work on: annotation-based approach. 
2. How to test it:

- once the changes are made in [notebook-controller](https://github.com/opendatahub-io/kubeflow/blob/v1.7-branch/components/notebook-controller/controllers/notebook_controller.go), build the image using the [Dockerfile](https://github.com/opendatahub-io/kubeflow/blob/v1.7-branch/components/notebook-controller/Dockerfile), use the following command.

`podman build -t nb-ctrl -f notebook-controller/Dockerfile .`
-  Setup ODH on a cluster, and scale down the opendatahub operator pod, once all the components are up.
`oc scale deployment opendatahub-operator-controller-manager --replicas=0 -n  openshift-operators`
- swap the image of notebook-controller with the image created and test a notebook.

**Comment by shalberd** [comment]
@harshad16 @rkpattnaik780 Have you seen this article in the past?
I wasn't aware we can upload configmaps instead of secrets for mapping into env values ... but this watching for changes mechanism in the article seems worthwhile to read.

https://itnext.io/working-with-kubernetes-configmaps-part-2-watchers-b6dd0e583d71
