### ISSUE TITLE
Deletion of the notebook-culler configmap causes Permission Denied on dashboard

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/kubeflow#200]
/kind bug

**What steps did you take and what happened:**
Customer has deleted "notebook-controller-culler-config" configmap in "redhat-ods-applications" namespace and now the Cluster Settings page in the ODH dashboard throws "HTTP request has failed" error.

Unable to save cluster settings as "HTTP request has failed error" occurs.

**What did you expect to happen:**
Edit cluster settings in ODH Dashboard and save.

JIRA: https://issues.redhat.com/browse/RHOAIENG-226

**Comment by chtyler** [comment]
Should this be declared in the release notes?

**Comment by harshad16** [comment]
@chtyler seems like it is included already:
https://file.emea.redhat.com/bmccolga/RHODS-8644_1-34_RelNotes/rh-hosted-cloud/html-single/Draft5_20231106/

**Comment by harshad16** [comment]
Check on creation and provide edit access to dashboard

**Comment by harshad16** [comment]
Closing this issue 
please follow the JIRA ticket for further updates.
