### ISSUE TITLE
[Bug] Notebook-controller unit-test are failing.  

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/kubeflow#203]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

While trying to run the notebook-controller unit test from the Makefile.
The go module build phase is failing.

```
note: module requires Go 1.19
# go.uber.org/multierr
/go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:13: undefined: atomic.Bool
note: module requires Go 1.19
```
```
  * could not run steps: step odh-notebook-controller-unit failed: "odh-notebook-controller-unit" test steps failed: "odh-notebook-controller-unit" pod "odh-notebook-controller-unit-unit" failed: could not watch pod: the pod ci-op-03sfhx4j/odh-notebook-controller-unit-unit failed after 1m49s (failed containers: test): ContainerFailed one or more containers exited
```

Reference: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/opendatahub-io_kubeflow/201/pull-ci-opendatahub-io-kubeflow-v1.7-branch-odh-notebook-controller-unit/1713548179993006080

**Comment by shalberd** [comment]
yes, I am hitting that error due to go.mod for kubeflow-notebook-controller and odh-notebook-controller unit tests in my PR

https://github.com/opendatahub-io/kubeflow/pull/133#issuecomment-1770843427
