### ISSUE TITLE
Kubeflow Notebooks and Elyra minio python package custom CA trust

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/kubeflow#233]
/kind feature

**Why you need this feature:**
This is more related to notebooks and the ca-bundle file injected with private and public CAs from Proxy config, those involved know what I mean.

The server IBM COS is based on a private PKI-based server certificate. I have the additional CAs plus publicly-trusted CAs mounted in as a ca-bundle and they are definitely in the mounted location. 

After I submit the pipeline, I get the following error related to IBM COS and CA trust:

`SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))`

In the past, in generated notebook CRs, we already added PIP_CERT and REQUESTS_CA_BUNDLE as env vars pointing to the ca-bundle file location in the container. It turns out Elyra, it uses a minio client to connect to any S3 storage, what they call COS ... cannot deal with non-publicly-trusted connections to S3 servers. The python client is called minio, apparently, it uses a mechanism called certify, but CA trust can be defined via an additional env var SSL_CERT_FILE.

https://github.com/minio/minio-py/issues/730#issuecomment-439556944

**Describe the solution you'd like:**
Setting env variable SSL_CERT_FILE 

to point to my (odh notebook controller-set) private-and-public-ca-bundle location in the odh notebook workbench worked, can connect with corporate S3 cluster now and save to bucket the Elyra pipeline metadata. I suggest we do this automatically via odh notebook controller.

desired:

```
[1001350000@jupyter-datascience-sven-elyra-test-0 ~]$ env | grep extracted
SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
PIP_CERT=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
```

**Anything else you would like to add:**
set here, related to proxy and CA trust config centrally at Openshift cluster level:

https://github.com/opendatahub-io/kubeflow/blob/v1.7-branch/components/odh-notebook-controller/controllers/notebook_webhook.go#L287

@harshad16 if ok with you, I will add a PR.
We had a similar issue in the past with python requests.get and env var REQUESTS_CA_BUNDLE solved it.

past issue https://github.com/opendatahub-io/kubeflow/issues/105

solved in past with PR https://github.com/opendatahub-io/kubeflow/pull/108

**Comment by shalberd** [comment]
added PR, thank you very much

**Comment by harshad16** [comment]
Thank you for your continuous effort. 
i will review the PR.
