### ISSUE TITLE
Notebook controller E2E tests in Openshift CI 

### ISSUE THREAD

**Issue by samuelvl** [opendatahub-io/kubeflow#30]
**Why you need this feature:**
When a new PR is opened, [E2E tests](https://github.com/opendatahub-io/kubeflow/tree/master/components/odh-notebook-controller/e2e) for the notebook controller should be triggered in Openshift CI.

**Describe the solution you'd like:**
Define a new job in [Openshift CI](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master.yaml#L42) to do the following tasks:
1. Create an Openshift cluster (assume last stable version).
2. Create a random namespace.
3. Deploy notebook controller in this namespace.
4. Run E2E tests.
5. Undeploy notebook controller.
6. Clean up Openshift cluster.

**Anything else you would like to add:**
Openshift CI E2E testing [documentation](https://docs.ci.openshift.org/docs/architecture/step-registry/).

/kind feature

**Comment by andrewballantyne** [comment]
We need to think on how we approach e2e as a whole. Hoping to learn more in a few hours about how/what can be gleamed from downstream tests.
