### ISSUE TITLE
odh-notebook-controller and notebook-controller crashloop when 200 notebooks are deployed

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/kubeflow#33]
/kind bug

**What steps did you take and what happened:**
After 200+ notebooks, I soon got an error when creating notebook resources that the service was not available.  Upon inspection, both the deployments for `odh-notebook-controller-manager` and `notebook-controller-deployment` were stuck in a crashloop state.  After increasing the deployments memory limits, I was able to continue creating notebooks.

**What did you expect to happen:**
To be able to create more than 200 notebooks on a cluster.

**Anything else you would like to add:**
Attached is the memory usage for the pods after creating 2000 notebooks, which is 1.3-1.6Gi.  a 4GB limit seems reasonable for perhaps a 5000 notebook limit per cluster, but it's up for debate how many we should support. 
![Screenshot from 2022-08-12 00-08-35](https://user-images.githubusercontent.com/1448375/184665868-566088c3-3e50-43e0-a76b-74060fb8288f.png)

**Environment:**
OCP 4.10.24
KF Version used in downstream 1.15

**Comment by samuelvl** [comment]
Resources for the kf-notebook-controller are defined here:

https://github.com/opendatahub-io/kubeflow/blob/321ead60e215a3eb9d579a1e3de657150606e24d/components/notebook-controller/config/overlays/openshift/manager_openshift_patch.yaml#L34-L40

And for the odh-notebook-controller here:

https://github.com/opendatahub-io/kubeflow/blob/321ead60e215a3eb9d579a1e3de657150606e24d/components/odh-notebook-controller/config/manager/manager.yaml#L46-L52

It's true that they are a bit small for enterprise environments.

**Comment by cfchase** [comment]
Going to follow up with PR from https://github.com/opendatahub-io/kubeflow/commit/596cebf2e9aaec5c5c7953f59db8f66020416c2a but I'm testing it out.
