### ISSUE TITLE
Inject current namespace/project as an ENV inside launched notebook container

### ISSUE THREAD

**Issue by akchinSTC** [opendatahub-io/kubeflow#39]
/kind feature

**Why you need this feature:**
See https://github.com/opendatahub-io/s2i-lab-elyra/issues/53

Elyra requires the namespace in order to pre-populate the default KFP runtime instance information. Right now we're parsing it from the JUPYTER_IMAGE env var but it would be preferable to have a dedicated env var for it to avoid it breaking in the future should the format of the value change.  

**Describe the solution you'd like:**
Add an ENV like `ODH_PROJECT_NAME` or `ODH_DEPLOY_NAMESPACE` with the namespace the container is deployed in as the value.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by samuelvl** [comment]
You can read it from the `/var/run/secrets/kubernetes.io/serviceaccount/namespace` file

**Comment by akchinSTC** [comment]
@samuelvl - thx, this is much more stable since its a k8s property
https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#directly-accessing-the-rest-api
