### ISSUE TITLE
Add GitHub Action to mirror git tags to quay tags

### ISSUE THREAD

**Issue by maroroman** [opendatahub-io/kubeflow#44]
/kind feature

**Why you need this feature:**
 It would be helpful to set up a similar system as in other odh repositories where each git tagsis mirrored into a quay tag of the same name for easier access.

**Describe the solution you'd like:**
Add a github action that uses skopeo to copy the git tag name into a new quay tag containing the same image.

**Comment by harshad16** [comment]
The repo would use the git commit hash-based quay tag, which is already pushed with the help of OpenShift-ci
https://github.com/openshift/release/blob/4f9b06cbb949dca709e9d4f9494da8c630eefe3d/ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-v1.7-branch.yaml#L94
https://github.com/openshift/release/blob/4f9b06cbb949dca709e9d4f9494da8c630eefe3d/ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-v1.7-branch.yaml#L78

As we have introduced the manifests, in-repo https://github.com/opendatahub-io/kubeflow/tree/v1.7-branch/components/base, include a tag based on a release would help, as we would have to update that
tag with another commit. 
The Requirement for github action to mirror git tags to quay tags is no longer required.
Thanks, closing the issue.
