### ISSUE TITLE
Sync Manifests with odh-manifests

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/kubeflow#56]
The manifests provided by the notebook controller do not match with the [odh-manifests](https://github.com/opendatahub-io/odh-manifests/tree/master/odh-notebook-controller) repo.

Sync the manifests, to easily mirror updates between the two repos

**Comment by LaVLaS** [comment]
Following up on our offline conversation, we need to investigate if we can move the changes configured by [odh-manifests/odh-notebook-controller/gen_odh_manifests.sh](https://github.com/opendatahub-io/odh-manifests/blob/master/odh-notebook-controller/gen_odh_manifests.sh) into this repo.

**Comment by VaishnaviHire** [comment]
This requires updates in Makefile for [odh-notebook-controller](https://github.com/opendatahub-io/kubeflow/blob/v1.6-branch/components/odh-notebook-controller/Makefile#L134). The manifests should match the [format](https://github.com/opendatahub-io/odh-manifests/tree/master/odh-notebook-controller) from odh-manifets repo.
