### ISSUE TITLE
Add script to run e2e Tests

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/kubeflow#59]
/kind feature

**Why you need this feature:**
Current implementation of e2e tests includes couple of make [targets](https://github.com/opendatahub-io/kubeflow/blob/v1.6-branch/components/odh-notebook-controller/Makefile#L163) that are responsible for deploying and cleaning up e2e tests. 

**Describe the solution you'd like:**
Automate the workflow with a script that -
- deploys the controllers
-  install dependencies 
-  creates an `artifacts` directory that has controller logs
- cleans up the test deployment

**Anything else you would like to add:**
This change will remove the dependency of test script in `openshift-ci`

**Comment by LaVLaS** [comment]
We should ensure that these test scripts can handle situations where the KUBECONFIG is read-only and we can't rely on modifications to the config for tracking the current target Namespace

See https://github.com/openshift/release/pull/36282#discussion_r1104595389
