### ISSUE TITLE
Add E2E testing for Notebook controller

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/kubeflow#6]
Create E2E tests for KFNBC and integrate them with OpenShift CI 

An initial test should perform following steps:
- Installs the CRD
- Creates a notebook object
- Verify the notebook pod is running
- Export controller logs for debugging

cc: @samuelvl

**Comment by samuelvl** [comment]
At the moment the available E2E tests are https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/ci/notebook_controller_tests.py and https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/cd/notebook_controller_tests.py
